# Generated by Django 4.1.7 on 2023-09-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reger',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='reger',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='Пороль'),
        ),
    ]
